# Generated by Django 4.2.20 on 2025-04-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('format_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('column_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['column_order'],
            },
        ),
        migrations.CreateModel(
            name='ItemColumnRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('row_order', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='format_app.itemcolumn')),
            ],
            options={
                'ordering': ['row_order'],
                'unique_together': {('column', 'row_order')},
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='column',
            name='row1',
        ),
        migrations.RemoveField(
            model_name='column',
            name='row2',
        ),
        migrations.RemoveField(
            model_name='column',
            name='row3',
        ),
        migrations.RemoveField(
            model_name='column',
            name='row4',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='item',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='choices',
            field=models.IntegerField(choices=[(576, '576'), (864, '864'), (1152, '1152'), (1200, '1200')], default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label_image',
            field=models.ImageField(blank=True, null=True, upload_to='.\\media\\uploads'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='format_app.customer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='density',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='pick',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ColorInfo',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='format_app.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='item_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='format_app.item'),
        ),
        migrations.AddField(
            model_name='itemcolumn',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='format_app.item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcolumn',
            unique_together={('item', 'column_order')},
        ),
    ]
