# Generated by Django 4.2.20 on 2025-05-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('format_app', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolumn',
            name='color_pick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcolumnrow',
            name='row_type',
            field=models.CharField(choices=[('color_name', 'Color Name'), ('dtex', 'DTEX'), ('color_number', 'Color Number')], default=3, max_length=20),
            preserve_default=False,
        ),
    ]
