# Generated by Django 4.2.20 on 2025-05-04 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('format_app', '0004_itemcolumn_color_pick_itemcolumnrow_row_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='Color Name')),
                ('color_dtex', models.PositiveIntegerField(verbose_name='DTEX')),
                ('color_number', models.CharField(max_length=50, verbose_name='Color Number')),
                ('rack_no', models.PositiveIntegerField(verbose_name='Rack No')),
                ('stock_kg', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock (kg)')),
            ],
            options={
                'verbose_name': 'Color Record',
                'verbose_name_plural': 'Color Records',
            },
        ),
    ]
